# Generated by Django 5.2.3 on 2025-06-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["status", "assignee"], name="tasks_task_status_a6a8c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["status"], name="tasks_task_status_4a0a95_idx"),
        ),
    ]
